name: Run unload_script.py after every push

on:
  push:
    branches:
      - upload

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Run unload_script.py
        run: |
          python upload_script.py -d ${{ github.workspace }}/Code -n "Github Actions #${{ github.run_number }}     by ${{github.actor}}" --tactical-module empty_tactical --strategic-module empty_strategic --password "eLY.Z[Ci^mrPN),TnA]<" -s pywar.ddns.net -p 5555
